#--------------------------------------------------------------------------------
# Values for this workshop - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
workshop_repo   : "https://github.com/nknadmin/2016-02-18-scw"
workshop_site   : "http://nknadmin.github.io/2016-02-18-scw"
#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
swc_blog        : "https://www.northwestknowledge.net"
swc_contact     : "admin@nkn.uidaho.edu"
swc_files       : "https://www.northwestknowledge.net"
swc_github      : "http://github.com/nknadmin"
swc_githubio    : "http://nknadmin.github.io/"
swc_installer   : "https://github.com/nknadmin/windows-installer/releases/download/v0.3/SWCarpentryInstaller.exe"
swc_site        : "http://www.northwestknowledge.net"
swc_twitter     : "http://twitter.com/swcarpentry"
swc_vm          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtSTZLQzF4aVB4NDQ&export=download"
swc_pre_survey  : "https://www.surveymonkey.com/r/swc_pre_workshop_v1?workshop_id="
swc_post_survey : "https://www.surveymonkey.com/r/swc_post_workshop_v1?workshop_id="
#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [tools]
